language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - 'node'
  - 'lts/*'
script: yarn ci
after_success: 
  - yarn global add travis-deploy-once
  - travis-deploy-once && yarn release
