language: node_js
cache: yarn
node_js:
  - node
  - lts/*
script: yarn run ci
jobs:
  include:
    - stage: semantic-release
      if: branch = master
      node_js: node
      script:
        - yarn run build
        - npx semantic-release@^15
