environment:
  nodejs_version: "Stable"

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version && npm --version
  - npm run ci

build: off
