name: CI

on: [push, pull_request]

env:
  CI: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: Echo versions used
      run: echo "node:" && node --version && echo "" && echo "npm:" && npm --version && echo "" && echo "yarn:" && yarn --version

    - name: Install dependencies
      run: yarn install

    - name: Run CI script
      run: yarn run ci

    - name: Release
      if: github.ref == 'refs/heads/master'
      run: yarn run release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
